name: ci

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: validate
      run: make validate

    - name: setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: install
      run: make install

    - name: lint
      run: make lint

    - name: test
      run: make test

    - name: coverage
      uses: paambaati/codeclimate-action@v6.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        coverageLocations: ${{ github.workspace }}/build/logs/clover.xml:clover
